spring.application.name=QUIZ-SERVICE
spring.datasource.url=jdbc:mysql://localhost:3306/micro_yt
spring.datasource.password=root
spring.datasource.username=root
spring.jpa.sql.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-bean-definition-overriding=true

spring.config.import=optional:configserver:http://localhost:8888
